/**
 * @see https://developers.google.com/youtube/iframe_api_reference
 */
export interface IYouTubePlayer {
  addEventListener: (event: string, listener: Function) => void,
  destroy: () => void,
  getAvailablePlaybackRates: () => number[],
  getAvailableQualityLevels: () => string[],
  getCurrentTime: () => number,
  getDuration: () => number,
  getIframe: () => Object,
  getOption: () => any,
  getOptions: () => any,
  setOption: () => void,
  setOptions: () => void,
  cuePlaylist: (playlist: string | string[] | {
    listType: string,
    list?: string,
    index?: number,
    startSeconds?: number,
    suggestedQuality?: string,
  }, index?: number, startSeconds?: number, suggestedQuality?: string) => void,
  loadPlaylist: (playlist: string | string[] | {
    listType: string,
    list?: string,
    index?: number,
    startSeconds?: number,
    suggestedQuality?: string,
  }, index?: number, startSeconds?: number, suggestedQuality?: string) => void,
  getPlaylist: () => string[],
  getPlaylistIndex: () => number,
  getPlaybackQuality: () => string,
  getPlaybackRate: () => number,
  getPlayerState: () => number,
  getVideoEmbedCode: () => string,
  getVideoLoadedFraction: () => number,
  getVideoUrl: () => string,
  getVolume: () => number,
  cueVideoById: (videoId: string | {
    videoId: string,
    startSeconds?: number,
    endSeconds?: number,
    suggestedQuality?: string,
  }, startSeconds?: number, suggestedQuality?: string) => void,
  cueVideoByUrl: (mediaContentUrl: string | {
    mediaContentUrl: string,
    startSeconds?: number,
    endSeconds?: number,
    suggestedQuality?: string,
  }, startSeconds?: number, suggestedQuality?: string) => void,
  loadVideoByUrl: (mediaContentUrl: string | {
    mediaContentUrl: string,
    startSeconds?: number,
    endSeconds?: number,
    suggestedQuality?: string,
  }, startSeconds?: number, suggestedQuality?: string)  => void,
  loadVideoById: (videoId: string | {
    videoId: string,
    startSeconds?: number,
    endSeconds?: number,
    suggestedQuality?: string,
  }, startSeconds?: number, suggestedQuality?: string) => void,
  isMuted: () => boolean,
  mute: () => void,
  nextVideo: () => void,
  pauseVideo: () => void,
  playVideo: () => void,
  playVideoAt: (index: number) => void,
  previousVideo: () => void,
  removeEventListener: (event: string, listener: Function) => void,
  seekTo: (seconds: number, allowSeekAhead: boolean) => void,
  setLoop: (loopPlaylists: boolean) => void,
  setPlaybackQuality: (suggestedQuality: string) => void,
  setPlaybackRate: (suggestedRate: number) => void,
  setShuffle: (shufflePlaylist: boolean) => void,
  setSize: (width: number, height: number) => Object,
  setVolume: (volume: number) => void,
  stopVideo: () => void,
  unMute: () => void,
  getSphericalProperties: () => {
    fov: number,
    yaw: number,
    pitch: number,
    roll: number,
    enableOrientationSensor: boolean,
  },
  setSphericalProperties: (properties: {
    fov?: number,
    yaw?: number,
    pitch?: number,
    roll?: number,
    enableOrientationSensor?: boolean,
  }) => void,
};

export enum PlayerState {
  BUFFERING = 3,
  ENDED = 0,
  PAUSED = 2,
  PLAYING = 1,
  UNSTARTED = -1,
  VIDEO_CUED = 5,
};

export interface IPlayerEventInfo {
  data: number,
  target: IYouTubePlayer,
};